##
## EPITECH PROJECT, 2023
## Raytracer
## File description:
## Makefile for NanoTekSpice
##

SRC = test_pool.cpp ../../../ThreadPool/ThreadPool.cpp

NAME = test

OBJ = $(SRC:.cpp=.o)

CPPFLAGS = -std=c++20 -Wall -Wextra -Werror -g -lpthread -pthread -fsanitize=thread -I../../../ThreadPool/

$(NAME): $(SRC)
	g++ $(CPPFLAGS) $(SRC) -o $(NAME)

all: $(NAME)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all
